codecov:
  notify:
    after_n_builds: 2
    wait_for_ci: false

  require_ci_to_pass: false
  token: 7102844c-b283-40bb-8e13-75dee404ec34  # notsecret  # repo-scoped, upload-only, stability in fork PRs

coverage:
  range: 100..100
  status:
    project:
      default:
        target: 100%
      app:
        target: 100%
        paths:
          - src/
      tests:
        target: 100%
        paths:
          - tests/

    patch:
      default:
        target: 100%
      app:
        target: 100%
        paths:
          - src/
      tests:
        target: 100%
        paths:
          - tests/
