{
 "title": "Digital Roadmap",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "roadmap-prod, roadmap-stage" }
  ]
 },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Datasource\n\n* Use `crcp01ue1-prometheus` for production cluster\n\n* Use `crcs02ue1-prometheus` for stage cluster\n\n# Namespace\n\n* Use `roadmap-stage` with `crcs02ue1-prometheus` datasource\n\n* Use `roadmap-prod` with `crcp01ue1-prometheus` datasource"
   }
  },
  {
   "title": "Python GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Collections Rate by Generation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(python_gc_collections_total{namespace=\"${namespace}\", job=\"roadmap-api\"}[5m])",
       "legendFormat": "{{pod}} (Generation: {{generation}})"
      }
     ]
    },
    {
     "title": "Collected Objects per Generation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(python_gc_objects_collected_total{namespace=\"${namespace}\", job=\"roadmap-api\"}[5m])\n",
       "legendFormat": "{{pod}} (Generation: {{generation}})"
      }
     ]
    },
    {
     "title": "GC Efficiency (Collected per Collection)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(python_gc_objects_collected_total{namespace=\"${namespace}\", job=\"roadmap-api\", generation=\"0\"}[5m])\n/\nrate(python_gc_collections_total{namespace=\"${namespace}\", job=\"roadmap-api\", generation=\"0\"}[5m])",
       "legendFormat": "{{pod}} (Generation: {{generation}})"
      }
     ]
    },
    {
     "title": "Uncollectable Objects (Potential Memory Leaks)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(python_gc_objects_uncollectable_total{namespace=\"${namespace}\", job=\"roadmap-api\"}[1h])",
       "legendFormat": "{{pod}} (Generation: {{generation}})"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "HTTP Request Throughput",
   "type": "timeseries",
   "description": "Total HTTP request rate handled by the roadmap-api. Useful for observing traffic volume over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(roadmap_http_requests_total{namespace=\"${namespace}\", job=\"roadmap-api\"}[1m])",
     "legendFormat": "{{pod}} ({{handler}}) ({{status}})"
    }
   ]
  },
  {
   "title": "Request Latency (p95, p99)",
   "type": "timeseries",
   "description": "Measures high-resolution request latency percentiles to detect performance degradation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(roadmap_http_request_duration_highr_seconds_bucket{namespace=\"${namespace}\", job=\"roadmap-api\"}[5m]))\n",
     "legendFormat": "{{pod}} (P95)"
    },
    {
     "expr": "histogram_quantile(0.99, rate(roadmap_http_request_duration_highr_seconds_bucket{namespace=\"${namespace}\", job=\"roadmap-api\"}[5m]))",
     "legendFormat": "{{pod}} (P99)"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "description": "Breakdown of requests by HTTP status code. Helps monitor errors (e.g., 500s) or spikes in 4xxs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod, status) (rate(roadmap_http_requests_total{namespace=\"${namespace}\",job=\"roadmap-api\"}[1m]))\n",
     "legendFormat": "{{pod}} ({{status}})"
    }
   ]
  },
  {
   "title": "Average Request & Response Size",
   "type": "timeseries",
   "description": "Tracks the average size of HTTP payloads. Sudden changes may indicate bugs or misuse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(roadmap_http_request_size_bytes_sum{namespace=\"${namespace}\", job=\"roadmap-api\"}[5m])\n/\nrate(roadmap_http_request_size_bytes_count{namespace=\"${namespace}\", job=\"roadmap-api\"}[5m])\n",
     "legendFormat": "Request ({{handler}})"
    },
    {
     "expr": "rate(roadmap_http_response_size_bytes_sum{namespace=\"${namespace}\", job=\"roadmap-api\"}[5m])\n/\nrate(roadmap_http_response_size_bytes_count{namespace=\"${namespace}\", job=\"roadmap-api\"}[5m])\n",
     "legendFormat": "Response  ({{handler}})"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "description": "Show how average latency changes over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(roadmap_http_request_duration_highr_seconds_sum[5m])\n/\nrate(roadmap_http_request_duration_highr_seconds_count[5m])\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}