apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.cee.redhat.com/rhel-lightspeed/digital-roadmap/digital-roadmap-backend-mirror/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "develop"

  creationTimestamp: null

  labels:
    appstudio.openshift.io/application: digital-roadmap-develop
    appstudio.openshift.io/component: digital-roadmap-develop
    pipelines.appstudio.openshift.io/type: build

  namespace: rhel-lightspeed-tenant
  name: digital-roadmap-pr

spec:
  params:
    - name: git-url
      value: '{{ source_url }}'

    - name: revision
      value: '{{ revision }}'

    - name: output-image
      value: quay.io/redhat-user-workloads/rhel-lightspeed-tenant/digital-roadmap:pr-{{ pull_request_number }}-latest

    - name: dockerfile
      value: /Containerfile

    - name: image-expires-after
      value: 5d

    - name: tag-prefix
      value: pr-{{ pull_request_number }}-

  pipelineRef:
    name: pipeline-build

  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
