name: Ruff

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
